### ISSUE TITLE
Got an error executing the project. Not sure if it's my installation the problem.

### ISSUE THREAD

**Issue by candy609** [Nexmo/stitch-demo#1]
[207.46.156.119-1522166485284.txt](https://github.com/Nexmo/stitch-demo/files/1852786/207.46.156.119-1522166485284.txt)

**Comment by ChrisGuzman** [comment]
You might have to change `const GATEWAY_URL` in stitch-demo/src/app/messaging.service.ts

See #2

**Comment by ChrisGuzman** [comment]
According to #4 looks like we solved the issue
